apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: gardener-extensions-validator-vsphere
webhooks:
- name: validation.vsphere.provider.extensions.gardener.cloud
  rules:
  - apiGroups:
    - "core.gardener.cloud"
    apiVersions:
    - v1alpha1
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - shoots
  failurePolicy: Fail
  objectSelector: {}
  namespaceSelector: {}
  clientConfig:
    url: "https://localhost:8010/webhooks/validate-shoot-vsphere"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGRENDQWZ3Q0NRQ2Z6VkpvamgxY0hEQU5CZ2txaGtpRzl3MEJBUXNGQURCTU1Sb3dHQVlEVlFRS0RCRkgKWVhKa1pXNWxjaUJGZUdGdGNHeGxjekVhTUJnR0ExVUVDd3dSVm1Gc2FXUmhkRzl5SUhaVGNHaGxjbVV4RWpBUQpCZ05WQkFNTUNXeHZZMkZzYUc5emREQWVGdzB5TURBek1UQXhNakExTlRKYUZ3MHpNREF6TURneE1qQTFOVEphCk1Fd3hHakFZQmdOVkJBb01FVWRoY21SbGJtVnlJRVY0WVcxd2JHVnpNUm93R0FZRFZRUUxEQkZXWVd4cFpHRjAKYjNJZ2RsTndhR1Z5WlRFU01CQUdBMVVFQXd3SmJHOWpZV3hvYjNOME1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTBhbk5PMmpuKzNHbzdsZTBiZ3dqclJNcFZRRHl4NTJCZ0UvbGpRRU44cjNZCnV2cmRhMklOUFBVSWlTVWpwNlFRYVgxSUNpdG0reEFnTXFhRjl1cUNSNmFucjNubkluQ0htdm5pc0s0c1orOWcKbkpUV0EwNG9YWHIzMkpYSHo1OEp3VVprZVp4Zm95ajFOK2dqTlhra3l3SkQreitHMWNHcnFDTW04MkxidldwQwpSWThKWU42eHgydzA3RDBHYjBBc3V0QUtseGYvdG9PcWZyVDhyLzB2N3NBZUltSWFkeGFaU3I5c1Z1bDdNUk1TCkltb3E0YkxFaUtmMktzb2dEamtjRG90dFFLTjlwZTloS2xYSVU0WTl3UlZQeVlsTVE1aDRYdkduL3E4ZHlVZ04KVDVhU1FRRVNBclFBY0lwTkZrRDg2NWlHNG1USXRlckcvbWJsWnh3dmpRSURBUUFCTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQnVMd1hqNkZMQzBJc01ZeEliOEZrR2F6TkR3d3NaQzFvN05BNzJWZWdwYTFlUTlsbFYrd2ZQCnlnNThNMHZvOWNXcHdxc011ZktCOGYrdEpQcHlVZjJvUGw2VS9yTjlOa0lnK2ErczlqYWxQOXNZQW9PNXp5VlgKMmYrK1ZzMFlDOURoUHhKMHYvRzZ0UUlnWmtMZGpScFhERytNR2wvNHRhTWR4MXpON1JEbUJITnpPN2M0VHJrbAozcFdYS1FqUmgzODFkTjhNSlBjWjNhVWJVSkxBaW12azZXVnMwTmdGL0JhcWxyRnJzaHVlbVJUV0p1MGR1cmRDCmVaVm1wdnNJYmtqQjhwb1dodndPTzBrV3d6Y0VPNEoxcjlrMVQyTGF4Q3RyR0E0Z1FCRUljbXhXSDgyRWIwS1IKeEFySy9qZDJNOUI4aitYNzF1SCtlMnp1ZVpQVkdNMlkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
